# Generated by Django 5.1.3 on 2024-11-22 22:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chatbot', models.CharField(max_length=20, unique=True)),
                ('nombre_comprador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESIMS.productcategory')),
                ('medida_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESIMS.productsize')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('estado_pedido', models.CharField(choices=[('Confirmado', 'Confirmado'), ('En preparación', 'En preparación'), ('Preparado', 'Preparado'), ('Cancelado', 'Cancelado')], default='Confirmado', max_length=20)),
                ('id_contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESIMS.contact')),
            ],
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESIMS.product')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESIMS.sale')),
            ],
        ),
    ]
