# Generated by Django 5.1.3 on 2024-11-22 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESIMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='id_contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ESIMS.contact'),
        ),
    ]
